=== drjolo/sharenav/Osm2GpsMid/style-file.dtd
<!ELEMENT legend (pois,ways)>
<!ELEMENT pois (key*)>
<!ELEMENT ways EMPTY>
<!ELEMENT key (value+)>
<!ELEMENT value (description, image?, namekey, namefallback?, scale, textscale?)>
<!ELEMENT description EMPTY>
<!ELEMENT image EMPTY>
<!ELEMENT namekey EMPTY>
<!ELEMENT namefallback EMPTY>
<!ELEMENT scale EMPTY>
<!ELEMENT textscale EMPTY>
<!ATTLIST key tag CDATA #REQUIRED>
<!ATTLIST value name CDATA #REQUIRED>
<!ATTLIST description desc CDATA #REQUIRED>
<!ATTLIST namekey tag CDATA #REQUIRED>
<!ATTLIST namefallback tag CDATA #REQUIRED>
<!ATTLIST scale scale CDATA #REQUIRED>
<!ATTLIST textscale scale CDATA #REQUIRED>
<!ATTLIST image src CDATA #REQUIRED>

=== drjolo/sharenav/Osm2GpsMid/style-file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE legend SYSTEM "style-file.dtd">
<!--
This is a sample style file for use with GpsMid. It allows
to specify which map features get converted from the osm
data to GpsMid. This can be changed at will, as long as it
conforms to style-file.dtd
-->
<legend>
  <pois>
	<key tag="place">
	   <value name="city">
		<description desc = "City"/>
		<namekey tag="name"/>
		<scale scale="300000"/>
	  </value>
	  <value name="town">
		<description desc = "Town"/>
		<namekey tag="name"/>
		<scale scale = "100000"/>
	  </value>
	  <value name="village">
		<description desc = "Village"/>
		<namekey tag="name"/>
		<scale scale = "30000"/>
	  </value>
	  <value name="hamlet">
		<description desc = "Hamlet"/>
		<namekey tag="name"/>
		<scale scale = "30000"/>
	  </value>
	  <value name="suburb">
		<description desc = "Suburb"/>
		<namekey tag="name"/>
		<scale scale = "20000"/>
	  </value>
	</key>
	<key tag="amenity">
	  <value name ="post_box">
		<description desc = "Post box"/>
		<image src="/post_box.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="1000"/>
	  </value>	
	  <value name ="post_office">
		<description desc = "Post box"/>
		<image src="/post_office.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="1000"/>
	  </value>	
	  <value name ="school">
		<description desc = "School"/>
		<image src="/school.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<scale scale="4000"/>
	  </value>
	  <value name ="telephone">
		<description desc = "Public telephone"/>
		<image src="/telephone.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale = "4000"/>
	  </value>
	  <value name ="restaurant">
		<description desc = "Restaurant"/>
		<image src="/restaurant.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="4000"/>
	  </value>
	  <value name ="hospital">
		<description desc = "Hospital"/>
		<image src="/hospital.png"/>
		<namekey tag="name"/>
		<scale scale="30000"/>
		<textscale scale="5000"/>
	  </value>
	  <value name ="pub">
		<description desc = "Pub"/>
		<image src="/pub.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="4000"/>
	  </value>
	  <value name ="atm">
		<description desc = "Cash machine"/>
		<image src="/atm.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="4000"/>
	  </value>
	  <value name ="cinema">
		<description desc = "Cinema"/>
		<image src="/cinema.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="4000"/>
	  </value>
	  <value name ="pharmacy">
		<description desc = "Pharmacy"/>
		<image src="/pharmacy.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="4000"/>
	  </value>
	  <value name ="place_of_worship">
		<description desc = "Church"/>
		<image src="/church.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="4000"/>
	  </value>
	  <value name ="fuel">
		<description desc = "Refueling station"/>
		<image src="/fuel.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="3000"/>		
	  </value>
	  <value name ="bicycle_parking">
		<description desc = "Bicycle parking"/>
		<image src="/bicycling.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="3000"/>		
	  </value>
	  <value name ="toilets">
		<description desc = "Public toilet"/>
		<image src="/toilets.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="3000"/>		
	  </value>
	  <value name ="recycling">
		<description desc = "Recycling"/>
		<image src="/recycling.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="3000"/>		
	  </value>
	  <value name ="library">
		<description desc = "Library"/>
		<image src="/library.png"/>
		<namekey tag="name"/>
		<scale scale="7500"/>
		<textscale scale="3000"/>		
	  </value>
	</key>
	<key tag="shop">
	   <value name="supermarket">
		<description desc = "Supermarket"/>
		<image src="/supermarket.png"/>
		<namekey tag="name"/>
		<scale scale="20000"/>
		<textscale scale="4000"/>
	  </value>
	</key>
	<key tag="highway">
	   <value name="bus_stop">
		<description desc = "Bus stop"/>
		<image src="/bus.png"/>
		<imageCentered value="true"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="4000"/>
	  </value>
	</key>
	<key tag="railway">
	   <value name="station">
		<description desc = "Railway station"/>
		<image src="/railstation.png"/>
		<imageCentered value="true"/>
		<namekey tag="name"/>
		<scale scale="35000"/>
		<textscale scale="10000"/>
	  </value>
	  <value name="tram_stop">
		<description desc = "Tram station"/>
		<image src="/railstation.png"/>
		<imageCentered value="true"/>
		<namekey tag="name"/>
		<scale scale="20000"/>
		<textscale scale="4000"/>
	  </value>
	  <key tag="tourism">
	   <value name="hotel">
		<description desc = "Hotel"/>
		<image src="/hotel.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="4000"/>		
	  </value>
	  <value name="museum">
		<description desc = "Museum"/>
		<image src="/museum.png"/>
		<namekey tag="name"/>
		<scale scale="10000"/>
		<textscale scale="4000"/>
	  </value>
	</key>
	</key>
  </pois>
  <ways/>
</legend>
